### ISSUE TITLE
Unicable does not work, how can I detect broken hardware?

### ISSUE THREAD

**Issue by HellGL** [perexg/satip-axe#104]
Hi,
my unicable setup (gss.Box, satip-axe V14, various clients on linux and  iOS) stopped working. I did not change anything, it just stopped on all clients. Connecting my gss.Box directly to the matrix and changing to quad lnb input setting I get a picture but as I only have one cable, of course only on one tuner. I suspected the Unicable switch (DUR-line SCR 514K) and got another switch on ebay (Preisner/Televes MSU 518NG, used but factory refurbished) which shows the same behaviour. Is there a way to check if the switch is really broken or if something else is going wrong? On the status website I get STR readings for the clients but no picture. Any ideas?

Regards,
HellG

**Comment by perexg** [comment]
Have you tried to play with the diseqc timing? issue #79
