### ISSUE TITLE
minisatip8 patch won't compile

### ISSUE THREAD

**Issue by kianusch** [perexg/satip-axe#105]
Compiling minisatip with the latest patches yields in an error and stops compiling ...

I belive 
`-		p = find_pid(aid, 0);`
`+		SPid p = find_pid(aid, 0);`
should actually be
`-		p = find_pid(aid, 0);`
`+		SPid *p = find_pid(aid, 0);`
... at least, on my setup, compiling works fine - with this change, and minisatip8 startup correctly.

**Comment by perexg** [comment]
Fixed. Thanks.
