### ISSUE TITLE
wiki connection via wifi 

### ISSUE THREAD

**Issue by Themesaul** [perexg/satip-axe#115]
Use satip-ax for months and it works perfect. I tried to connect a wifi adapter via USB and configure it but I could not. It would be great if it was included in the wiki.

**Comment by perexg** [comment]
There are no plans to support this. Use any cheap WIFI AP with the client functionality.

**Comment by Themesaul** [comment]
I understand that you do not want to give support to wifi using a USB adapter. Thank you very much too.
