### ISSUE TITLE
Multistream support

### ISSUE THREAD

**Issue by perexg** [perexg/satip-axe#126]
Appearently STV0900 demodulators with chip id 0x30+ supports multistream.

The axe hardware has chip id 0x30:

<pre>
~ # axehelper i2c_reg_read 0xd0 0xf100
0x30
</pre>

**Linux kernel code:**

https://github.com/torvalds/linux/blob/64c5e530ac2cab7e710c3bd08ef8594a016e4f9a/drivers/media/dvb-frontends/stv090x.c#L3433-L3474

https://linux-media.vger.kernel.narkive.com/RyQdvAhf/patch-stv0900-multistream-support

**Goals:**

- inject the current closed source DVBAPI driver from Inverto to support it
  - old DVBAPI (use another way to control PLS/MIS filter - sysfs or proc)
- extend minisatip to support PLS/MIS settings

**Comment by perexg** [comment]
Ok, build 15-rc5 is out with the multistream support, tvh supports the newly added SAT>IP extension, too.

**Comment by perexg** [comment]
Build 15-rc6 supports both GOLD and ROOT PLS schemes (with latest tvh).

**Comment by perexg** [comment]
It seems that there's just one PLS scrambling algorithm and ROOT/GOLD just specifies a different way to get the starting value for the descrambler:

https://github.com/DigitalDevices/dddvb/blob/master/apps/pls.c

The COMBO seems like a bug..

**Comment by perexg** [comment]
BTW: https://github.com/oe-alliance/satip-client/pull/10 , even enigma2 on my openpli can do multistream through SAT>IP protocol now !!!!

**Comment by gpoerzgen** [comment]
Is it possible, that you provide a satipclient package for the vu solo 2?

**Comment by perexg** [comment]
@gpoerzgen : http://s000.tinyupload.com/?file_id=42666432231835511189

**Comment by perexg** [comment]
Note that if you like to activate the TCP data transport add tcpdata=1 option like:

<pre>
0=desc:minisatip,ipaddr:192.168.100.237,tuner_type:DVB-S,uuid:11223344-9999-0000-b7ae-0022b7f0056e,vtuner_type:satip_client,tcpdata:1
</pre>

**Comment by gpoerzgen** [comment]
Thanks, I will test it tonight

**Comment by perexg** [comment]
Build15 final is out with the multistream support.
