### ISSUE TITLE
oscamd binary missing in Build 15

### ISSUE THREAD

**Issue by langimike** [perexg/satip-axe#128]
Hi,

when trying to start oscamd in Build 15, I get the following message. I could not find any oscamd binary on the filesystem - am I missing something (need to install an external package) or is oscamd missing in the build?

```
/ # /etc/init.d/oscamd
/etc/init.d/oscamd: exec: line 33: oscamd: not found
/ # which oscamd
/ # find -name *oscam*
./mnt/data/satip-axe/sysconfig/oscam
./mnt/data/satip-axe/sysconfig/oscam/oscam.conf
./etc/init.d/oscamd
```

**Comment by phaze75** [comment]
Same here. oscamd is already missing in RC6.

**Comment by perexg** [comment]
Fixed in https://github.com/perexg/satip-axe/releases/tag/build15-fix1 .
