### ISSUE TITLE
Manual configuration of nameserver

### ISSUE THREAD

**Issue by pbriesch** [perexg/satip-axe#13]
Hi,

how do I specify the IP of the nameserver when not using dhcp?

In the config I didn't find an example therefore I have tried IPV4_NAMESERVER="192.168.1.1", but this doesn't work.
 
Thanks for looking into it!

Paul

````
#IPV4 config
#
#IPV4="dhcp"
#or
IPV4="192.168.1.55"
IPV4_NETMASK="255.255.255.0"
IPV4_BROADCAST="192.168.1.255"
IPV4_GATEWAY="192.168.1.1"
IPV4_NAMESERVER="192.168.1.1"

**Comment by perexg** [comment]
Put resolv.conf file to /etc/sysconfig/ directory.

**Comment by pbriesch** [comment]
Yes, this works. Thank you.
