### ISSUE TITLE
Bad Tune

### ISSUE THREAD

**Issue by estimadarocha** [perexg/satip-axe#132]
![image](https://user-images.githubusercontent.com/17991728/47951198-3d645580-df55-11e8-95b4-2aae9556761e.png)

@perexg do you know why this happen?

brand new tvheadend installation (HTS Tvheadend 4.3-1519~g1222de114-dirty) but can't scan channels from tvheadend!

**Comment by Trujulu** [comment]
Maybe low quality?

**Comment by estimadarocha** [comment]
@Trujulu no! completely fine! if i grab mux with wget signal its ok!

**Comment by estimadarocha** [comment]
@Trujulu forget it...

https://tvheadend.org/issues/5310

thanks for the help!
