### ISSUE TITLE
No minisatip logs in syslog

### ISSUE THREAD

**Issue by jlazkano** [perexg/satip-axe#133]
Hello,

I activate the syslog to send logs to a centralized server. The problem is that there are no minisatip logs, there are just tuner initialization and DHCP related logs.

How could I activate the minisatip logs?

I want to know if there are CC errors in signal reception.

Regards.

**Comment by perexg** [comment]
Check minisatip manual (-l). But the CC check code is removed in the axe minisatip binaries to save CPU time. You may use the webif to see, if hardware CC errors (increases) - the functionality is nearly identical.
