### ISSUE TITLE
Oscam 11516

### ISSUE THREAD

**Issue by bylderup** [perexg/satip-axe#145]
a version with build 11516 (or newer) would be nice

**Comment by antaril** [comment]
yes that would be cool

**Comment by Knacki2212** [comment]
yes, version 11516 (or newer) would be fantastic

**Comment by bylderup** [comment]
my interim solution:
Downlad an Oscam 11517 sh4 binary file 
SSH (e.g. use Winscp) to Digibit R1
upload binary file to /etc/sysconfig/
rename file to oscamsh4 and chmod 
new file in /etc/sysconfig/ named myboot
edit myboot :
#!/bin/sh
exec /etc/sysconfig/oscamsh4 -c /etc/sysconfig/oscam -u
save file and chmod
edit /etc/sysconfig/config file:
disable buildin OSCAMD with #
enable CUSTOMD, remove # in line CUSTOMD="/etc/sysconfig/myboot"
save config file

reboot and have fun

**Comment by antaril** [comment]
thx works like a charme ;)

**Comment by Knacki2212** [comment]
thank you... :-)

**Comment by jandy123** [comment]
Sorry, but what is the added value of oscam 11516 ???

**Comment by perexg** [comment]
https://github.com/perexg/satip-axe/issues/155
