### ISSUE TITLE
Support for prom/node_exporter 

### ISSUE THREAD

**Issue by hkuehl** [perexg/satip-axe#152]
Please excuse my limited Linux-know-how, but would it be possible to get [node_exporter](https://github.com/prometheus/node_exporter) running on this firmware? I trial’n’error-tested some of the current releases but they were incompatible.

**Comment by perexg** [comment]
I'm not a big fan of this. The snmp request looks better in my eyes: https://github.com/perexg/satip-axe/issues/144 .

**Comment by hkuehl** [comment]
Looks fine for me! Closing...
