### ISSUE TITLE
Install gcc

### ISSUE THREAD

**Issue by Javito68** [perexg/satip-axe#173]
Hello everyone,

  how can I install gcc to compile:
   https://github.com/akosinov/unicable/tree/master/dsqsend
   gcc senddsq.c -o senddsq
  or how can I compile it?
Thanks and best regards!

**Comment by Javito68** [comment]
Hi,

  fixed, had not seen: perexg add senddsq package
  a question:
  what does the parameter [-f <frontend nr>] of senddsq mean?

Thanks!

**Comment by Jalle19** [comment]
https://github.com/akosinov/unicable/blob/master/dsqsend/senddsq.c#L56 seems like it selects the frontend.

**Comment by perexg** [comment]
It seems resolved.
