### ISSUE TITLE
Jess on Dibibit R1 with Jalle19/satip-axe does not work

### ISSUE THREAD

**Issue by melias122** [perexg/satip-axe#179]
Sorry for commenting here, but https://github.com/Jalle19/satip-axe does not have Issues enabled.

I just tried Jalle19/satip-axe (Build 16) and it does not work. I cannot tune any channel using Tvheadend or VLC directly.

I have been using minisatip8 with `MINISATIP8_OPTS=-9 0 -j 0:0-1210,1:1-1420,2:2-1680,3:3-2040`, now with Jalle19 build `MINISATIP_OPTS="-9 0 -j 0:0-1210,1:1-1420,2:2-1680,3:3-2040"`, I tried different args from `minisatip --help` but cant get it work.

**Comment by Jalle19** [comment]
I re-enabled issues: https://github.com/Jalle19/satip-axe/issues, please open an issue there instead and close this one.
