### ISSUE TITLE
Autostart Minisatip

### ISSUE THREAD

**Issue by pcr91** [perexg/satip-axe#189]
Hello! Install the latest version of minisatip. I have the config file configured with the tuners to use only one tuner (I use Universal LNB).

The problem is that minisatip does not start automatically. I have to start it with the command minisatip -F -S 1-3: 0 If I restart the digibit, I have to rerun it for it to work.
What can happen?

Thanks a lot.

**Comment by perexg** [comment]
https://github.com/perexg/satip-axe/blob/master/dist/README - onfiguration file is in /etc/sysconfig/config
