### ISSUE TITLE
Usage with “Wideband” LNBs?

### ISSUE THREAD

**Issue by zoe72a** [perexg/satip-axe#191]
Sky Q ships with an LNB which separates horizontal and vertical outputs via two cables to the sky q box allowing it to have numerous tuners via two cables, this is what they call a “wideband” lnb however I am vaugely under the impression thats the wrong name and for some random reason people just decided that was what it was called so apologies if I am using the incorrect terminology.

Can I configure this firmware to allow me to use this type of LNB with my TELESTAR DIGIBIT R1?

**Comment by Jalle19** [comment]
It should be supported, the option is `-8` or `--quattro-hiband`
