### ISSUE TITLE
Oscam with CCAM Protocol

### ISSUE THREAD

**Issue by armaghanshahzad** [perexg/satip-axe#20]
Hi,

Can I descremble channels directly fro Inverto IDL 400S?
Regards
Armaghan

**Comment by pbriesch** [comment]
Please look at the README: https://github.com/manio/vdr-plugin-dvbapi
pmt_mode = **4**

**Comment by pbriesch** [comment]
@armaghanshahzad 
Please note that at this time the Inverto box is missing a Linux kernel driver to support decryption by its hardware. The CPU of the box is to slow to descramble a channel. So even if your setup is fine you will not get a descrambled stream, maybe a still picture.

**Comment by perexg** [comment]
It's dup of issue #17  .
