### ISSUE TITLE
DCHP has to be enabled in Webif before booting satip-axe

### ISSUE THREAD

**Issue by pbriesch** [perexg/satip-axe#22]
Hi,

I cannot connect to the box via Ethernet. The network light stays dark after the Knight Rider intro. The box does not get an IP address. However, the lights on the Ethernet socket blink as there were some traffic.

Any suggestions?

Paul

**Comment by perexg** [comment]
Try idl4k.usbresetusb script to reset the old configuration stored in flash which may cause the boot failure. Just keep the .fw file and replace idl4k.scr with idl4k.cfgresetusb . But boot only once with this boot script otherwise the configuration will be renamed each time.

**Comment by pbriesch** [comment]
Resetting the configuration did not work. However, I could fix the problem:
In the Webif of the original firmware I had to change the IP setting back from fixed to dhcp. Then it worked. There is some other user in the vdr-portal who reported the same issue: http://www.vdr-portal.de/board19-verschiedenes/board52-andere-hardware/p1250510-initial-release-of-the-satip-axe-firmware-is-available-minisatip-for-digibit-r1-dsi-400-idl400s/#post1250510

**Comment by perexg** [comment]
It seems like a side effect of something, because the satip-axe firmware has own network config which should be independent from the original firmware (which stores this config to EEPROM). I'll try to look into this issue. Thanks.

**Comment by perexg** [comment]
Unfortunately, I cannot reproduce this on my box (the booting process works fine with static network settings in the original firmare). I cannot do much without a dump from the serial console.

**Comment by pbriesch** [comment]
Maybe you could mention this potential problem in the README recommending to set DHCP on in the original firmware.

**Comment by perexg** [comment]
Done.
