### ISSUE TITLE
4 tuners with 1 coax cable: possible?

### ISSUE THREAD

**Issue by PsychoRS** [perexg/satip-axe#30]
Hi,

I'm using satip-axe in a Inverto Multibox, stability and performance are top. But I have one question...

Can I configure minisatip for using all 4 tuners of the Multibox with only one coaxial cable? Right now I have a 6-way splitter splitting the signal (Astra 19.2, single way LNB) for getting all 4 coaxial inputs populated. Is that so weird?

With my VU+ Solo2, I can set tuner 2 as "bridged" or "slave" to tuner 1 so I can get the benefits of having 2 tuners with only one antenna cable. Is this possible with the Inverto and minisatip?

Thanks in advance.

**Comment by perexg** [comment]
Look to README.md - Minisatip config, you want to use these options (assuming that your coax is in input 1 - '-L 0:1,0:2,0:3' . Note that the reception is limited to h/v,lo-hi combination, of course.

https://github.com/perexg/satip-axe/blob/master/dist/README
