### ISSUE TITLE
Upgrade minisatip version

### ISSUE THREAD

**Issue by m4rcs** [perexg/satip-axe#31]
Hi, 

I was trying to get minisatip working with oscam. During debugging I noticed that -o parameter gets totally ignored. This is due to the old version of minisatip (commit: 54df9348e7bd7e6075f54f1b93ec4ad36429abe0). 

Please update minisatip to the latest version.

Greets Marc

**Comment by 9000h** [comment]
I had asked also long before #24

**Comment by perexg** [comment]
Upgrading to recent minisatip requires some work (many patches and fixes specific to the axe boxes are there). I concentrate to tvheadend at the moment. Also, someone tested the sh4 processor speed regarding DES and the speeds are very low. I suggest to not do the descrambling on this box until we can enable the hardware support (yes, hw can do descrambling in hardware), but we don't have proper STAPI drivers from Inverto ( issue #4 ).

**Comment by perexg** [comment]
Descrambling speed for dvbcsa library on sh4 CPU used in idl4k:

<pre>
# /tmp/benchdec 
* CSA decryption bench *
 benchmarking with 256 TS packets
 benchmarking with 512 TS packets
 benchmarking with 1024 TS packets
 benchmarking with 2048 TS packets
 benchmarking with 4096 TS packets
 benchmarking with 8192 TS packets
 benchmarking with 16384 TS packets
 benchmarking with 32768 TS packets
 - 65280 packets proceded, 3.8 Mbits/s
</pre>

**Comment by m4rcs** [comment]
Is this good or bad?

**Comment by perexg** [comment]
One SD channel which uses a standard bandwidth.. Useless.. I put this value just for a reference.

Anyway, I have new minisatip working (without descrambling).

**Comment by perexg** [comment]
Resolved in #45 .
