### ISSUE TITLE
Triax TSS400 supported?

### ISSUE THREAD

**Issue by victornet** [perexg/satip-axe#32]
Hi,

does anybody know if Triax TSS400 tuner is supported too?

Regards,
Simon

**Comment by perexg** [comment]
Could you disassemble the box and take detailed photos of the internal board ?

**Comment by victornet** [comment]
Sorry, but i didn't own this box (yet).

**Comment by 9000h** [comment]
you can find a picture and some details here:
http://www.vdr-portal.de/board19-verschiedenes/board52-andere-hardware/p1165917-erste-sat-ip-ger%C3%A4te-vorgestellt-hardware-und-erfahrungs-sammel-thread/#post1165917

**Comment by perexg** [comment]
It seems that Triax has totaly another firmware so it's incompatible with satip-axe.
