### ISSUE TITLE
Unicable configuration

### ISSUE THREAD

**Issue by PsychoRS** [perexg/satip-axe#38]
Hi,

Is it possible to configure minisat IP for using 4 userbands (1 per tuner) with only one coax cable in Unicable mode?

I'm planning to buy a 8-userband Unicable Multiswitch, and use two Inverto Multiboxes (8 tuners) with a unicable 2-way splitter (so thats 1 coax cable per box, 1 userband per tuner, 8 total tuners/userbands).

Are the userband's frequencies configurable (per tuner) when using the -X parameter in minisatip-opts?

  - example 2: unicable: MINISATIP_OPTS="-u 0:1-1420,1:0-1210,2:2-1680,3:3-2040"
   - example 3: unicable coax in input 2: MINISATIP_OPTS="-X 1"

Does that means that I can use MINISATIP_OPTS="-u 0:userband1, 1:userband2, 2:userband3. 3:userband4 -X 0" for assigning a userband for each tuner and coax only in input 1?

Thanks in advance

**Comment by perexg** [comment]
Unicable can transmit 8 selected transponders (for 8 tuners) per one wire. See http://www.inverto.tv/guide/?p=12 for example. The unicable LNB / switches defines fixed slot number + frequency where the selected transponder is transmitted in the local coaxial cable. Check unicable specification.
