### ISSUE TITLE
Minisatip is not sending ECM to oscam

### ISSUE THREAD

**Issue by crazy888** [perexg/satip-axe#40]
Hi,
after having some problems with minisatip at the beginning there is now another one.
When trying to tune a encrypted channel, minisatip is not sending any request to oscam.
Oscam is running fine and dvbapi is connected without any errors.
Do I need to set up additionally parameters to turn on minisatip sending to oscam?

**Comment by perexg** [comment]
We don't support descrambling. The CPU has no power to to so and for hw descrambling see #17 .
