### ISSUE TITLE
Network Issue Inverto Box

### ISSUE THREAD

**Issue by Quarcs** [perexg/satip-axe#41]
Hello,

I got some problems with my Inverto Box:
I boot up from an usb drive. I have not flashed the device. 
The LAN Port is not stable. Dmesg shows me, that the port goes up and down

PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 1000/Full

That is why I don't get a stable connection to it. I lose a lot of packages at a ping request. Do you have an idea how to fix the issue? 

Thanks a lot!

**Comment by perexg** [comment]
Wrong gigabit connection ? You may try to force 1000M with ethtool (which is in the satip-axe firmware), but it would be better to resolve the culprit.

**Comment by pbriesch** [comment]
It could help to force the connection to 100 M on the switch if it is a manageable switch.

**Comment by Quarcs** [comment]
@perexg 
Tried:
ethtool -s eth0 speed 1000 duplex full

Config now:

ethtool eth0
Settings for eth0:
	Supported ports: [ TP AUI BNC MII FIBRE ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  1000baseT/Full 
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Speed: 1000Mb/s
	Duplex: Full
	Port: MII
	PHYAD: 1
	Transceiver: external
	Auto-negotiation: on
	Supports Wake-on: ug
	Wake-on: g
	Current message level: 0x0000003f (63)
			       drv probe link timer ifdown ifup
	Link detected: yes


==> Still not stable
==> Will try another TP-Cable (Cat 5e)

@pbriesch: It is an unmanaged switch

**Comment by 9000h** [comment]
@Quarcs if you have it on a FritzBox try to disable the Green/ECO mode for this port

**Comment by pbriesch** [comment]
Try to force **100** M with ethtool.

**Comment by Quarcs** [comment]
@9000h Good idea, I got a FritzBox, but Green/ECO mode is already disabled :(

@pbriesch I will try :)

**Comment by dreamcat4** [comment]
Or bad gigabit cable. Which can work for some device and not others @ 1000 MBits speed.

**Comment by Quarcs** [comment]
Changed cable from cat5e to cat6. No improvement.

@pbriesch have forced to 100M. It is working at the moment. Hope it will stay like this... Thanks a lot :-) 

Will let this ticket open for a while and will close it soon if there are no issues for a while

**Comment by Quarcs** [comment]
same problems  again. Has only helped a few minutes :(

**Comment by Quarcs** [comment]
That's my full dmesg. Perhaps it helps...

Linux version 2.6.32.42_stm24_0208-idl4k_7108 (perex@stlinux.perex-int.cz) (gcc version 4.5.3 20111123 (STMicroelectronics/Linux Base 4.5.3-99) (GCC) ) #43 PREEMPT Thu Aug 6 10:51:35 CEST 2015
Boot params:
... MOUNT_ROOT_RDONLY - 00000001
... RAMDISK_FLAGS     - 00000000
... ORIG_ROOT_DEV     - 00000200
... LOADER_TYPE       - 00000000
... INITRD_START      - 00000000
... INITRD_SIZE       - 00000000
Booting machvec: idl4k
Node 0: start_pfn = 0x70000, low = 0x8f000
Zone PFN ranges:
  Normal   0x00070000 -> 0x0008f000
Movable zone start PFN for each node
early_node_map[1] active PFN ranges
    0: 0x00070000 -> 0x0008f000
On node 0 totalpages: 126976
free_area_init_node: node 0, pgdat 81459dbc, node_mem_map 8291e000
  Normal zone: 992 pages used for memmap
  Normal zone: 0 pages reserved
  Normal zone: 125984 pages, LIFO batch:31
Inverto idl4k board initialisation
STx7108 version 2.x, HOST core
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 125984
Kernel command line:  console= hw=16001000000000000000000000000000 sn=1S81C11301000121 uuid=F9E168D1428C4048B48509BADE8FC7C0 revBoot=stm24_0056-B0_80-idl4k-rev47 console=ttyAS0,115200 bigphysarea=20000
bpa2: partition 'bigphysarea' created at 0x72d02000, size 80000 kB (0x04e20000 B)
PID hash table entries: 2048 (order: 1, 8192 bytes)
Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
PVR=04909300 CVR=60880000 PRR=0000a320
I-cache : n_ways=2 n_sets=512 way_incr=16384
I-cache : entry_mask=0x00003fe0 alias_mask=0x00003000 n_aliases=4
D-cache : n_ways=2 n_sets=512 way_incr=16384
D-cache : entry_mask=0x00003fe0 alias_mask=0x00003000 n_aliases=4
Memory: 381184k/507904k available (3365k kernel code, 1091k data, 20132k init)
Hierarchical RCU implementation.
NR_IRQS:500
Failed to enable clk CLKA0_REF, ignoring
Failed to enable clk CLKA0_PLL0LS, ignoring
Failed to enable clk CLKA1_REF, ignoring
Failed to enable clk CLKA1_PLL0LS, ignoring
Console: colour dummy device 80x25
console [ttyAS0] enabled
sh_tmu: TMU0 used for clock events
sh_tmu: TMU0 used for periodic clock events
sh_tmu: TMU1 used as clock source
Calibrating delay loop... 595.96 BogoMIPS (lpj=297984)
Mount-cache hash table entries: 512
CPU: STx7108
NET: Registered protocol family 16
bio: create slab <bio-0> at 0
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
Switching to clocksource TMU1
NET: Registered protocol family 2
IP route cache hash table entries: 4096 (order: 2, 16384 bytes)
TCP established hash table entries: 16384 (order: 5, 131072 bytes)
TCP bind hash table entries: 16384 (order: 4, 65536 bytes)
TCP: Hash tables configured (established 16384 bind 16384)
TCP reno registered
NET: Registered protocol family 1
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
[STM]: [PM]: HoM support registered
[STM]: [PM]: [HoM]: Early console @ 0xfd733000
Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
Slow work thread pool: Starting up
Slow work thread pool: Ready
JFFS2 version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
fuse init (API version 7.13)
msgmni has been set to 744
alg: No test for stdrng (krng)
io scheduler noop registered
io scheduler anticipatory registered (default)
io scheduler deadline registered
io scheduler cfq registered
STMicroelectronics ASC driver initialized
stm-asc.0: ttyAS0 at MMIO 0xfd733000 (irq = 108) is a stm-asc
brd: module loaded
NAND device: Manufacturer ID: 0x2c, Chip ID: 0xf1 (Micron NAND 128MiB 3,3V 8-bit)
Bad block table found at page 65472, version 0x01
Bad block table found at page 65408, version 0x01
cmdlinepart partition parsing not available
Creating 5 MTD partitions on "stm-nand-flex.0":
0x000000000000-0x000000020000 : "nand-env"
0x000000020000-0x000000420000 : "nand-system"
0x000000420000-0x000002420000 : "nand-fw1"
0x000002420000-0x000004420000 : "nand-fw2"
0x000004420000-0x000008000000 : "nand-data"
STMMAC driver:
	platform registration... 
	done!
	PMT module supported
	DWMAC1000 - user ID: 0x10, Synopsys ID: 0x33
	Enhanced descriptor structure
	eth0 - (dev. name: stmmaceth - id: 1, IRQ #88
	IO base addr: 0xfe730000)
STMMAC MII Bus: probed
eth0: PHY ID 001cc915 at 0 IRQ 0 (1:00)
eth0: PHY ID 001cc915 at 1 IRQ 25 (1:01) active
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
stm_usb_probe: usb_phy_clk clock not found for stm-usb.0
stm-ehci stm-ehci.0: STMicroelectronics EHCI Host Controller
stm-ehci stm-ehci.0: new USB bus registered, assigned bus number 1
stm-ehci stm-ehci.0: irq 124, io mem 0xfe0ffe00
stm-ehci stm-ehci.0: USB 0.0 started, EHCI 1.00
usb usb1: configuration #1 chosen from 1 choice
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
stm-ohci stm-ohci.0: STMicroelectronics OHCI Host Controller
stm-ohci stm-ohci.0: new USB bus registered, assigned bus number 2
stm-ohci stm-ohci.0: irq 127, io mem 0xfe0ffc00
usb usb2: configuration #1 chosen from 1 choice
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 1 port detected
stm_usb_probe: usb_phy_clk clock not found for stm-usb.1
stm-ehci stm-ehci.1: STMicroelectronics EHCI Host Controller
stm-ehci stm-ehci.1: new USB bus registered, assigned bus number 3
stm-ehci stm-ehci.1: irq 125, io mem 0xfe1ffe00
stm-ehci stm-ehci.1: USB 0.0 started, EHCI 1.00
usb usb3: configuration #1 chosen from 1 choice
hub 3-0:1.0: USB hub found
hub 3-0:1.0: 1 port detected
stm-ohci stm-ohci.1: STMicroelectronics OHCI Host Controller
stm-ohci stm-ohci.1: new USB bus registered, assigned bus number 4
stm-ohci stm-ohci.1: irq 128, io mem 0xfe1ffc00
usb usb4: configuration #1 chosen from 1 choice
hub 4-0:1.0: USB hub found
hub 4-0:1.0: 1 port detected
stm_usb_probe: usb_phy_clk clock not found for stm-usb.2
stm-ehci stm-ehci.2: STMicroelectronics EHCI Host Controller
stm-ehci stm-ehci.2: new USB bus registered, assigned bus number 5
stm-ehci stm-ehci.2: irq 126, io mem 0xfe2ffe00
stm-ehci stm-ehci.2: USB 0.0 started, EHCI 1.00
usb usb5: configuration #1 chosen from 1 choice
hub 5-0:1.0: USB hub found
hub 5-0:1.0: 1 port detected
stm-ohci stm-ohci.2: STMicroelectronics OHCI Host Controller
stm-ohci stm-ohci.2: new USB bus registered, assigned bus number 6
stm-ohci stm-ohci.2: irq 129, io mem 0xfe2ffc00
usb usb6: configuration #1 chosen from 1 choice
hub 6-0:1.0: USB hub found
hub 6-0:1.0: 1 port detected
Initializing USB Mass Storage driver...
usbcore: registered new interface driver usb-storage
USB Mass Storage support registered.
usbcore: registered new interface driver usbserial
USB Serial support registered for generic
usb 1-1: new high speed USB device using stm-ehci and address 2
usb 1-1: configuration #1 chosen from 1 choice
scsi0 : SCSI emulation for USB Mass Storage devices
usb-storage: device found at 2
usb-storage: waiting for device to settle before scanning
usbcore: registered new interface driver usbserial_generic
usbserial: USB Serial Driver core
i2c /dev entries driver
stm i2c clock = 100500000, ns_per_clk = 9
stm i2c modified clock = 50250000, ns_per_clk = 19
stm i2c clock = 100500000, ns_per_clk = 9
stm i2c modified clock = 50250000, ns_per_clk = 19
at24 1-0050: 8192 byte 24c64 EEPROM (writable)
sh_tmu: TMU0 kept as earlytimer
sh_tmu: TMU1 kept as earlytimer
STMicroelectronics - Coprocessors st231 Init
st-coprocessor-0: No RAM reserved
st231.0 Coprocessor -------------------------------------------
    not configured!
---------------------------------------------------------------
st-coprocessor-1: No RAM reserved
st231.1 Coprocessor -------------------------------------------
    not configured!
---------------------------------------------------------------
st-coprocessor-2: No RAM reserved
st231.2 Coprocessor -------------------------------------------
    not configured!
---------------------------------------------------------------
TCP cubic registered
NET: Registered protocol family 10
IPv6 over IPv4 tunneling driver
NET: Registered protocol family 17
[STM]: [PM]: Suspend support registered
drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
Freeing unused kernel memory: 20132k freed
Empty flash at 0x004e09c0 ends at 0x004e1000
Empty flash at 0x004e19c0 ends at 0x004e2000
Empty flash at 0x004e29c0 ends at 0x004e3000
Empty flash at 0x004e39c0 ends at 0x004e4000
Empty flash at 0x004e49c0 ends at 0x004e5000
Empty flash at 0x004e59c0 ends at 0x004e6000
Empty flash at 0x004e69c0 ends at 0x004e7000
Empty flash at 0x004e79c0 ends at 0x004e8000
Empty flash at 0x004e89c0 ends at 0x004e9000
Empty flash at 0x004e99c0 ends at 0x004ea000
Empty flash at 0x004ea9c0 ends at 0x004eb000
Empty flash at 0x004eb9c0 ends at 0x004ec000
Empty flash at 0x004ec9c0 ends at 0x004ed000
Empty flash at 0x004ed9c0 ends at 0x004ee000
Empty flash at 0x004ee9c0 ends at 0x004ef000
Empty flash at 0x004ef9c0 ends at 0x004f0000
Empty flash at 0x004f09c0 ends at 0x004f1000
Empty flash at 0x004f19c0 ends at 0x004f2000
Empty flash at 0x004f29c0 ends at 0x004f3000
Empty flash at 0x004f39c0 ends at 0x004f4000
Empty flash at 0x004f49c0 ends at 0x004f5000
Empty flash at 0x004f59c0 ends at 0x004f6000
Empty flash at 0x004f69c0 ends at 0x004f7000
Empty flash at 0x004f79c0 ends at 0x004f8000
Empty flash at 0x004fa11c ends at 0x004fa800
Empty flash at 0x004fb1c0 ends at 0x004fb800
Empty flash at 0x004fc1c0 ends at 0x004fc800
Empty flash at 0x004fd1c0 ends at 0x004fd800
Empty flash at 0x004fe1c0 ends at 0x004fe800
Empty flash at 0x004ff1c0 ends at 0x004ff800
Empty flash at 0x00ec09c0 ends at 0x00ec1000
Empty flash at 0x00ec19c0 ends at 0x00ec2000
Empty flash at 0x00ec29c0 ends at 0x00ec3000
Empty flash at 0x00ec39c0 ends at 0x00ec4000
Empty flash at 0x00ec49c0 ends at 0x00ec5000
Empty flash at 0x00ec59c0 ends at 0x00ec6000
Empty flash at 0x00ec69c0 ends at 0x00ec7000
Empty flash at 0x00ec79c0 ends at 0x00ec8000
Empty flash at 0x00ec89c0 ends at 0x00ec9000
Empty flash at 0x00ec99c0 ends at 0x00eca000
Empty flash at 0x03a609c0 ends at 0x03a61000
Empty flash at 0x03a61b3c ends at 0x03a62000
jffs2_scan_inode_node(): CRC failed on node at 0x03a627c4: Read 0xffffffff, calculated 0xca14308e
Empty flash at 0x03a62ba8 ends at 0x03a63000
Empty flash at 0x03a63b4c ends at 0x03a64000
Empty flash at 0x03a64af8 ends at 0x03a65000
jffs2_scan_eraseblock(): Node at 0x03a657f8 {0x1985, 0xe002, 0x00000229) has invalid CRC 0xe0021985 (calculated 0x523f00ad)
jffs2_scan_eraseblock(): Magic bitmask 0x1985 not found at 0x03a657fc: 0x0229 instead
jffs2_scan_inode_node(): CRC failed on node at 0x03a65fec: Read 0xffffffff, calculated 0x7cf1b81f
Empty flash at 0x03a66104 ends at 0x03a66800
Empty flash at 0x03a6714c ends at 0x03a67800
Empty flash at 0x03a68228 ends at 0x03a68800
Empty flash at 0x03a6926c ends at 0x03a69800
Empty flash at 0x03a6a238 ends at 0x03a6a800
Empty flash at 0x03a6b294 ends at 0x03a6b800
Empty flash at 0x03a6c2ac ends at 0x03a6c800
Empty flash at 0x03a6d1d8 ends at 0x03a6d800
Empty flash at 0x03a6e194 ends at 0x03a6e800
Empty flash at 0x03a6f1fc ends at 0x03a6f800
Empty flash at 0x03a70278 ends at 0x03a70800
Empty flash at 0x03a7128c ends at 0x03a71800
stapi_core: module license 'ST Microelectronics' taints kernel.
Disabling lock debugging due to kernel taint
Load module sttbx_early_core
Load module stos_core [?]		by insmod (pid 468)
Load module stcommon_core [?]		by insmod (pid 468)
Load module sttbx_core [?]		by insmod (pid 468)
Load module stevt_core [?]		by insmod (pid 468)
Load module stavmem_core [?]		by insmod (pid 468)
Load module stbuffer_core [?]		by insmod (pid 468)
Load module stclock_core [252]		by insmod (pid 468)
Load module stpower_core [251]		by insmod (pid 468)
Load module stpio_core [?]		by insmod (pid 468)
Load module stfdma_core [250]		by insmod (pid 468)
Load module stinject_core [?]		by insmod (pid 468)
Load module stnet_core [?]		by insmod (pid 468)
Load module stpti5_core [?]		by insmod (pid 468)
Load module stcommon_ioctl [249]	by insmod (pid 474)
Load module sttbx_ioctl [248]		by insmod (pid 474)
Load module stevt_ioctl [247]		by insmod (pid 474)
Load module stavmem_ioctl [246]		by insmod (pid 474)
Load module stbuffer_ioctl [245]	by insmod (pid 474)
Load module stpower_ioctl [244]		by insmod (pid 474)
Load module stpio_ioctl [243]		by insmod (pid 474)
Load module stfdma_ioctl [240]		by insmod (pid 474)
Load module stinject_ioctl [239]	by insmod (pid 474)
Load module stnet_ioctl [238]		by insmod (pid 474)
Load module stsys_ioctl [237]		by insmod (pid 474)
Load module stpti5_ioctl [236]		by insmod (pid 474)
I2C-Bus AXE mangle module loaded
[demod900] setup [num_demods 4]
[pll6120] setup [num_plls:4] [clk:30000000] [bbgain:16]
[fe] Checking lut 0xC1ACE62C
[fe] Checking lut 0xC1ACE662
[fe] Checking lut 0xC1ACE62C
[fe] Checking lut 0xC1ACE690
[dmx] ... init 0
[fta_fe] FE Initialization done, res 0
[dmx-ts] ... init 0
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00eca62c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec962c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec862c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec762c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec662c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec562c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec462c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec362c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec262c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec162c: read 0xd6d2ab23, calculated 0x567c8132.
JFFS2 notice: (461) check_node_data: wrong data CRC in data node at 0x00ec062c: read 0xd6d2ab23, calculated 0x567c8132.
USB Serial support registered for cp210x
usbcore: registered new interface driver cp210x
cp210x: v0.09:Silicon Labs CP210x RS232 serial adaptor driver
USB Serial support registered for pl2303
usbcore: registered new interface driver pl2303
pl2303: Prolific PL2303 USB to serial adaptor driver
USB Serial support registered for FTDI USB Serial Device
usbcore: registered new interface driver ftdi_sio
ftdi_sio: v1.5.0:USB FTDI Serial Converters Driver
stmmac: Rx Checksum Offload Engine supported
	TX Checksum insertion supported
scsi 0:0:0:0: Direct-Access     JetFlash TS256MJF2A/120   8.07 PQ: 0 ANSI: 2
sd 0:0:0:0: [sda] 501760 512-byte logical blocks: (256 MB/245 MiB)
sd 0:0:0:0: Attached scsi generic sg0 type 0
usb-storage: device scan complete
sd 0:0:0:0: [sda] Write Protect is off
sd 0:0:0:0: [sda] Mode Sense: 03 00 00 00
sd 0:0:0:0: [sda] Assuming drive cache: write through
sd 0:0:0:0: [sda] Assuming drive cache: write through
sda: detected capacity change from 0 to 256901120
 sda: sda1
sd 0:0:0:0: [sda] Assuming drive cache: write through
sd 0:0:0:0: [sda] Attached SCSI removable disk
eth0: no IPv6 routers present
PHY: 1:01 - Link is Up - 1000/Full
PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 1000/Full
PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 100/Full
@@@@@@@@@@@@ fe_open 0
@@@@@@@@@@@@ fe_open 1
@@@@@@@@@@@@ fe_open 2
@@@@@@@@@@@@ fe_open 3
@@@@@@@@@@@@ fe_open 0
@@@@@@@@@@@@ fe_open 1
@@@@@@@@@@@@ fe_open 2
@@@@@@@@@@@@ fe_open 3
@@@@@@@@@@@@ fe_open 0
@@@@@@@@@@@@ fe_open 1
@@@@@@@@@@@@ fe_open 2
@@@@@@@@@@@@ fe_open 3
@@@@@@@@@@@@ fe_open 0
@@@@@@@@@@@@ fe_open 1
@@@@@@@@@@@@ fe_open 2
@@@@@@@@@@@@ fe_open 3
@@@@@@@@@@@@ fe_open 0
@@@@@@@@@@@@ fe_open 1
@@@@@@@@@@@@ fe_open 2
@@@@@@@@@@@@ fe_open 3
@@@@@@@@@@@@ fe_open 0

**Comment by perexg** [comment]
Could you try the new satip-axe firmware with the updated ethernet driver?

http://s000.tinyupload.com/?file_id=78443875428972064634

List of changes:

https://github.com/perexg/satip-axe/blob/master/dist/README (upcoming)

Please, give me feedback.

**Comment by Quarcs** [comment]
It was also not working well with the original firmware. So I send it back to the manufacturer. I will try it, when I get the device back. I will write you directly. Thanks for your help @perexg  :-)

**Comment by perexg** [comment]
Closing. Re-open if you have issues with new box.

**Comment by fedecarnales** [comment]
I'm having the same problem, the network keeps disconnecting. Dmesg shows repeated instances of:

PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 1000/Full

I tried forcing it to 100m with ethtool but I lose the connection altogether until I reboot, but after rebooting it's back to 1000m.

I also have connection problems with the original firmware. Might be a faulty unit but I can't send it back. Is there any way to get a USB Ethernet adapter to work so as to bypass the internal ethernet chip? I tried an adapter I have (with Realtek RTL8153 chipset) and it didn't seem to recognize it.

Thanks!

**Comment by ant-thomas** [comment]
Sorry to reopen this, I seem to be suffering from the same issue.
I've been using my Digibit R1 without issue on satip-axe for over 2 years, up until about a month ago and it keeps suffering from the issue
```PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 1000/Full```

Could the box have become faulty?
I'm using the same cable as from day 1.

**Comment by ant-thomas** [comment]
It could well have just been the cable, which is odd since it hasn't been moved for 2 years!
Hopefully the change has fixed it.

**Comment by SerialVelocity** [comment]
I'm also hitting the same issue with a bunch of link down/up in my logs:
```
PHY: 1:01 - Link is Down
PHY: 1:01 - Link is Up - 1000/Full
```

@ant-thomas @fedecarnales Is your device behind a switch? If I bypass the switch I don't get this issue.

The latest official Digisat R1 firmware (V1.24.0.156) doesn't seem to have this problem but previous versions did.
