### ISSUE TITLE
Network access problem

### ISSUE THREAD

**Issue by aleceuta** [perexg/satip-axe#42]
Hi,

I have a problem with satip-axe firmware on my TELESTAR DIGIBIT R1, I use a pendrive with last version release satip-axe-201508061051-10, my problem is when I try change for static ip, edit the file /etc/sysconfig/config and change the relative part of networks, change, the line :

IPV4="static"

and uncomment

IPV4="192.168.3.210"
IPV4_NETMASK="255.255.255.0"
IPV4_BROADCAST="192.168.3.255"
IPV4_GATEWAY="192.168.3.50" 

save the file and reboot Telestar

I test with a ping and work.

But when access by web say an 404 error
and in the networks place on my pc does not appear.

but really the problem because after I came back to try DHCP configuration for try

by mistake put the line in

IPV4="DHCP" 

DHCP in upper letter

and save file and reboot

since then it does not respond to ping and nothing (ssh, telnet, etc..)

I try idl4k.cfgresetusb rename to idl4k.scr

With the original firmware (TELESTAR) works fine on dhcp and static.

Help me please.

**Comment by aleceuta** [comment]
some method to restore the file /etc/sysconfig/config

**Comment by aleceuta** [comment]
No one can tell me what I can do?

**Comment by perexg** [comment]
Have you really tried idl4k.cfgresetusb to idl4k.scr and boot the satip-axe firmware again ? Note that you must have satip-axe-201508061051-10.fw file on stick, too!

**Comment by aleceuta** [comment]
yes, yes I put the two files idl4k.cfgresetusb rename to idl4k.scr and satip-axe-201508061051-10.fw, any question the file /etc/sysconfig/config is the flash of the telestar?

**Comment by perexg** [comment]
Yes, it file in the internal flash, but I tested the reset procedure several times, so I really don't know why you cannot enter it.... The box should be available through DHCP IP as after the first installation. You may check, if there are some DHCP requests when you boot the satip-axe firmware with idl4k.cfgresetusb u-boot configuration.

**Comment by aleceuta** [comment]
when I try to reset with the file idl4k.cfgresetusb, after a few minutes the original firmware starts?, even when the stick punctured, that is normal

**Comment by perexg** [comment]
no, the satip firmware should be started with the default configuration; something is wrong on your side; you should see the led effect (blinking from left to right and back)  - it means that something is downloaded from USB

note that some USB sticks does not work..

**Comment by perexg** [comment]
also check the USB slot - it must be upper one..

**Comment by aleceuta** [comment]
yes on the upper when put with file idl4k.cfgresetusb not Knight Rider effect

**Comment by perexg** [comment]
show me the directory content for your usb stick, also, I think that the stick must have a parition....

**Comment by perexg** [comment]
also, tell me, if you use the satip-axe-201508061051-10.usb as idl4k.scr , do you see the Knight Rider effect ?

**Comment by aleceuta** [comment]
yes when use satip-axe-201508061051-10.usb as idl4k.scr. I see Knight Rider effect

**Comment by perexg** [comment]
sorry, I see it... the cfgresetusb file is broken.. wait

**Comment by perexg** [comment]
ok, download the idl4k.cfgresetusb and follow the section 'Recovery from the wrong configuration:' in https://github.com/perexg/satip-axe/blob/master/dist/README

**Comment by aleceuta** [comment]
I see your new file, I put, but I don`t see Knight Rider effect

**Comment by aleceuta** [comment]
is necesary special partition, I use fat32,

**Comment by aleceuta** [comment]
Now I use the original firmware with static ip, for use  idl4k.cfgresetusb is necesary put dhcp on original firmware.

**Comment by aleceuta** [comment]
![2016-02-01](https://cloud.githubusercontent.com/assets/16822333/12732644/df0a2366-c936-11e5-98ac-e3a97f990d97.png)

**Comment by perexg** [comment]
You don't follow updated README. The firmware file must be satip-axe.fw (I tried to make the recovery script universal for all 10+ firmwares (future)).

**Comment by aleceuta** [comment]
Ok it works, solved, thanks.
