### ISSUE TITLE
Build number 11

### ISSUE THREAD

**Issue by perexg** [perexg/satip-axe#45]
This is alpha/beta version of build 11.

<pre>
    - updated stmmac ethernet driver from latest stlinux kernel
      - linux-sh4-2.6.32.y - _stm24_0217
      - enabled Realtek PHY module (RTL8211E)
      - disable scatter-gather, increase ring descriptors (from 256 to 512)
    - updated axe_fe.ko kernel module
      - it should fix the weak reception on tuners 3 and 4
    - updated dropbear to 2015.71
      - changed from dss host key to rsa host key (for latest openssl)
    - updated nfsutils to 1.3.3
    - updated nano to 2.4.3
    - updated oscam to 11211
    - updated axe_dmxts.ko kernel module from idl4k-1.24.0.156
    - minisatip accepts -M option to skip first MPEG-TS packets from demuxer
      - the default value is 35 (to skip packets from previous tune)
    - minisatip can handle multiple unicable groups
    - minisatip - improve/fix LNB standby/power handling
    - added second minisatip binary (minisatip5 - based on 0.5.30 version)
      - add new lines to /etc/sysconfig/config from /etc/config.default
    - added python-3.5.1
</pre>

## Builds (latest is first)

**satip-axe-201602291458-11**: http://s000.tinyupload.com/?file_id=07538728056691070023

  - many minisatip/minisatip5 fixes, minisatip 0.5 seems stable now
  - updated minisatip5 to 0.5.30
  - moved python-3.5.1 to an additional package
  - created multicast-rtp script (package) for permanent multicast subscriptions
  - packages (unpack to /mnt/data/satip-axe/packages)
    - http://s000.tinyupload.com/?file_id=09779354606695819704
  - it's release candidate number 1

**satip-axe-201602232118-11**: http://s000.tinyupload.com/?file_id=07149528303672465745

  - replaced axe_fe.ko kernel module (frontend) - to latest from firmware 1.0.0.156
    - it should fix issue with tuners 3&4
  - minisatip(both): added -P switch, improve/fix LNB standby/power handling
  - added python-3.5.1

**satip-axe-201602202312-11**: http://s000.tinyupload.com/?file_id=16496123055715927145

 - improved minisatip (multiple unicable groups, -Z option)
 - improved minisatip5 (multiple unicable groups, -Z option, * as adapter for diseqc options)
 - dropbear: changed from dss host key to rsa host key (for latest openssl)
 - updated axe_dmxts.ko kernel module from idl4k-1.24.0.156

**satip-axe-201602171601-11**: http://s000.tinyupload.com/?file_id=48159403741321059962

 - fixed: minisatip,minisatip5 - -M option (packet skipping)
 - fixed: minisatip5 - tuner allocation
 - added: minisatip5 - diseqc timing control, diseqc fast switch

**satip-axe-201602162124-11**: http://s000.tinyupload.com/?file_id=06751229885275141251
  - fixed: minisatip5 - crashes when /status.html is touched when minisatip is active

**satip-axe-201602161748-11**: http://s000.tinyupload.com/?file_id=80075445712266167575

**Comment by x23piracy** [comment]
Hi,

will oscam now work via stapi? can the box stream descambled streams?


Regards X23

**Comment by clandmeter** [comment]
You are including minisatip5, but what is it used for?

**Comment by perexg** [comment]
It's based on minisatip 0.5.30. An updated version which uses threads to control, better diseqc control (support for uncommitted switches, diseqc timing control) and many improvements (status page). But I'm maintaining the older 0.1.84 version, too.

**Comment by perexg** [comment]
I created a short document which explains some newly implemented features in minisatip binaries in build 11:

https://github.com/perexg/satip-axe/blob/master/dist/minisatip.md

**Comment by bylderup** [comment]
I have two files now in mnt/data/satip-axe/packages : multicast-rtp-1.tar.gz and Python-3.5.1.tar.gz
unpacking these files, too ??  which tar params ? -xf or -xzf -C ?

**Comment by perexg** [comment]
No, just reboot the box. The unpacking is automatic on boot (see /etc/init.d/rcS). The root filesystem is in ramdisk, so everything is lost on boot.

**Comment by bylderup** [comment]
Latest beta is fine for free TV but I have problems with some paytv channels

**Comment by m4tt075** [comment]
A note on the upgrade process:
I downloaded the 11.fw file to /mnt/data and ran "upgrade-fw ./11.fw" from there. The first two flash attempts failed with errors, the third one seemed to work. However, after entering "reboot" following the on-screen instructions, the network connection did not come up again. Powered the box off and on again, no change, network would not come up. Had to flash the firmware via USB (following the dist instructions) to make it work again. It's up and running now. Will test and report back. But just in case, anyone else runs into similar issues...

**Comment by perexg** [comment]
@m4tt075 : If you like, create a new issue for this. If the verification succeed, it should work.

**Comment by perexg** [comment]
The release 201603051934-11 is available at https://github.com/perexg/satip-axe/tree/master/dist .

* another fixes in minisatip/minisatip5
* added fetch-package script
* upgrade-fw can be run only from / or /root directory

**Comment by m4tt075** [comment]
@perexg: Thanks. Not needed anymore. Apparently I ran upgrade-fw from the wrong directory. Just updated again to the release version from /root and no problems whatsoever. Thanks again for all your amazing work on satip-axe as well as TVH!
