### ISSUE TITLE
Feature request for next build

### ISSUE THREAD

**Issue by timehlers** [perexg/satip-axe#59]
Hi Perexg,

I would like to see the kernel feature:

CONFIG_VLAN_8021Q=y

activated in the next build. I have a setup with a untagged and a tagged VLAN on the box, where the box is reachable in both networks. I tried CONFIG_VLAN_8021Q on my kernel build and the ethernet driver seems to support tagged VLAN, so it would be a nice feature to be able to stream to different network segments via tagged VLANs in your firmware, too.

Thanks and best

Tim

**Comment by perexg** [comment]
Added to build 12.
