### ISSUE TITLE
satip: Cannot get http://192.168.1.30:8080/0: Success

### ISSUE THREAD

**Issue by paluseb** [perexg/satip-axe#62]
@satip o you use minisatip5 and on what version of TVH?
You can post your config?
I ask because I have the same problem as you advance.
More here:
https://github.com/perexg/satip-axe/issues/57

**Comment by perexg** [comment]
Could you give output from 'ps', 'logread' and 'netstat -an' ?

But it looks like a network configuration issue rather a bug in the satip-axe .

**Comment by paluseb** [comment]
Logs give later. I'm surprised such action client satip Panasonic tv. Unencrypted channels (even those test UHD) work properly if I use the original software Telestar R1 as well minisatip. When the factory firmware if the decryption is made in the TV through the CI module also everything works properly. But when using minisatip and CI module for video noise appears. The same situation is where descrambling takes place in a stream tvheadend.

**Comment by perexg** [comment]
I doubt about the last sentence. Note that almost all SAT>IP clients use UDP transport which may be intolerant to ethernet packet drops. I know that the original firmware does some packet scheduling to eliminate this issue (but it's not 100%). TVH with RTP/AVP/TCP enabled (embedded RTSP data mode) should be fine.

**Comment by paluseb** [comment]
satip-axe login: root
Password:

Welcome to SATIP-AXE server 201605311610-12

~ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/busybox init
    2 root       0:00 [kthreadd]
    3 root       0:00 [ksoftirqd/0]
    4 root       0:00 [events/0]
    5 root       0:00 [khelper]
   13 root       0:00 [async/mgr]
   14 root       0:00 [pm]
  174 root       0:00 [sync_supers]
  176 root       0:00 [bdi-default]
  178 root       0:00 [kblockd/0]
  186 root       0:00 [ksuspend_usbd]
  191 root       0:00 [khubd]
  194 root       0:00 [kseriod]
  209 root       0:00 [rpciod/0]
  215 root       0:00 [kswapd0]
  216 root       0:00 [aio/0]
  217 root       0:00 [nfsiod]
  218 root       0:00 [kslowd000]
  219 root       0:00 [kslowd001]
  221 root       0:00 [crypto/0]
  309 root       0:00 [mtdblockd]
  378 root       0:00 [scsi_eh_0]
  379 root       0:00 [usb-storage]
  461 root       0:00 syslogd -C256
  464 root       0:00 [jffs2_gcd_mtd4]
  473 root       0:00 [STTBX_CircBuf_O]
  474 root       0:00 [STFDMA_ClbckMgr]
  475 root       0:00 [STFDMA_ClbckMgr]
  476 root       0:00 [STFDMA_ClbckMgr]
  485 root       0:00 [kfe-0]
  492 root       0:00 [kdmxts_64]
  493 root       0:00 [kdmxts_64]
  494 root       0:00 [kdmxts_64]
  495 root       0:00 [kdmxts_64]
  496 root       0:00 [kdmxts_64]
  497 root       0:00 [kdmxts_64]
  498 root       0:00 [kdmxts_64]
  499 root       0:00 [kdmxts_64]
  500 root       0:00 [kdmxts_64]
  501 root       0:00 [kdmxts_64]
  502 root       0:00 [kdmxts_64]
  503 root       0:00 [kdmxts_64]
  504 root       0:00 [kdmxts_64]
  505 root       0:00 [kdmxts_64]
  506 root       0:00 [kdmxts_64]
  507 root       0:00 [kdmxts_64]
  508 root       0:00 [kdmxts_64]
  509 root       0:00 [kdmxts_64]
  510 root       0:00 [kdmxts_64]
  511 root       0:00 [kdmxts_64]
  512 root       0:00 [kdmxts_64]
  513 root       0:00 [kdmxts_64]
  514 root       0:00 [kdmxts_64]
  515 root       0:00 [kdmxts_64]
  516 root       0:00 [kdmxts_64]
  517 root       0:00 [kdmxts_64]
  518 root       0:00 [kdmxts_64]
  519 root       0:00 [kdmxts_64]
  520 root       0:00 [kdmxts_64]
  521 root       0:00 [kdmxts_64]
  522 root       0:00 [kdmxts_64]
  523 root       0:00 [kdmxts_64]
  524 root       0:00 [kdmxts_64]
  525 root       0:00 [kdmxts_64]
  526 root       0:00 [kdmxts_64]
  527 root       0:00 [kdmxts_64]
  528 root       0:00 [kdmxts_64]
  529 root       0:00 [kdmxts_64]
  530 root       0:00 [kdmxts_64]
  531 root       0:00 [kdmxts_64]
  532 root       0:00 [kdmxts_64]
  533 root       0:00 [kdmxts_64]
  534 root       0:00 [kdmxts_64]
  535 root       0:00 [kdmxts_64]
  536 root       0:00 [kdmxts_64]
  537 root       0:00 [kdmxts_64]
  538 root       0:00 [kdmxts_64]
  539 root       0:00 [kdmxts_64]
  540 root       0:00 [kdmxts_64]
  541 root       0:00 [kdmxts_64]
  542 root       0:00 [kdmxts_64]
  543 root       0:00 [kdmxts_64]
  544 root       0:00 [kdmxts_64]
  545 root       0:00 [kdmxts_64]
  546 root       0:00 [kdmxts_64]
  547 root       0:00 [kdmxts_64]
  548 root       0:00 [kdmxts_64]
  549 root       0:00 [kdmxts_64]
  550 root       0:00 [kdmxts_64]
  551 root       0:00 [kdmxts_64]
  552 root       0:00 [kdmxts_64]
  553 root       0:00 [kdmxts_64]
  554 root       0:00 [kdmxts_64]
  555 root       0:00 [kdmxts_64]
  556 root       0:00 [kdmxts_64]
  557 root       0:00 [kdmxts_64]
  558 root       0:00 [kdmxts_64]
  559 root       0:00 [kdmxts_64]
  560 root       0:00 [kdmxts_64]
  561 root       0:00 [kdmxts_64]
  562 root       0:00 [kdmxts_64]
  563 root       0:00 [kdmxts_64]
  564 root       0:00 [kdmxts_64]
  565 root       0:00 [kdmxts_64]
  566 root       0:00 [kdmxts_64]
  567 root       0:00 [kdmxts_64]
  568 root       0:00 [kdmxts_64]
  569 root       0:00 [kdmxts_64]
  570 root       0:00 [kdmxts_64]
  571 root       0:00 [kdmxts_64]
  572 root       0:00 [kdmxts_64]
  573 root       0:00 [kdmxts_64]
  574 root       0:00 [kdmxts_64]
  575 root       0:00 [kdmxts_64]
  576 root       0:00 [kdmxts_64]
  577 root       0:00 [kdmxts_64]
  578 root       0:00 [kdmxts_64]
  579 root       0:00 [kdmxts_64]
  580 root       0:00 [kdmxts_64]
  581 root       0:00 [kdmxts_64]
  582 root       0:00 [kdmxts_64]
  583 root       0:00 [kdmxts_64]
  584 root       0:00 [kdmxts_64]
  585 root       0:00 [kdmxts_64]
  586 root       0:00 [kdmxts_64]
  587 root       0:00 [kdmxts_64]
  588 root       0:00 [kdmxts_64]
  589 root       0:00 [kdmxts_64]
  590 root       0:00 [kdmxts_64]
  591 root       0:00 [kdmxts_64]
  592 root       0:00 [kdmxts_64]
  593 root       0:00 [kdmxts_64]
  594 root       0:00 [kdmxts_64]
  595 root       0:00 [kdmxts_64]
  596 root       0:00 [kdmxts_64]
  597 root       0:00 [kdmxts_64]
  598 root       0:00 [kdmxts_64]
  599 root       0:00 [kdmxts_64]
  600 root       0:00 [kdmxts_64]
  601 root       0:00 [kdmxts_64]
  602 root       0:00 [kdmxts_64]
  603 root       0:00 [kdmxts_64]
  604 root       0:00 [kdmxts_64]
  605 root       0:00 [kdmxts_64]
  606 root       0:00 [kdmxts_64]
  607 root       0:00 [kdmxts_64]
  608 root       0:00 [kdmxts_64]
  609 root       0:00 [kdmxts_64]
  610 root       0:00 [kdmxts_64]
  611 root       0:00 [kdmxts_64]
  612 root       0:00 [kdmxts_64]
  613 root       0:00 [kdmxts_64]
  614 root       0:00 [kdmxts_64]
  615 root       0:00 [kdmxts_64]
  616 root       0:00 [kdmxts_64]
  617 root       0:00 [kdmxts_64]
  618 root       0:00 [kdmxts_64]
  619 root       0:00 [kdmxts_64]
  694 root       0:00 /lib/modules/axe/main_axe.out
  702 root       0:00 [stptiAPI_EventN]
  703 root       0:00 [stptiAPI_LiveMo]
  704 root       0:00 sh -c /root/main_init.sh
  705 root       0:00 {exe} ash /root/main_init.sh
  709 root       0:00 sleep 999999999
  767 root       0:00 /sbin/udhcpc -f -S -p /var/run/udhcpc.pid -s /etc/init.d/
  768 root       0:00 {ntpd} /bin/sh /etc/init.d/ntpd
  769 root       0:00 mountd -F --no-nfs-version 4
  770 root       0:00 {satip} /bin/sh /etc/init.d/satip
  771 root       0:00 /usr/sbin/telnetd -F -l /bin/login
  772 root       0:00 dropbear -F
  773 root       0:00 /usr/sbin/inetd -f
  775 root       0:00 /usr/sbin/crond -f -S -c /etc/sysconfig/crontabs
  782 root       0:00 /bin/busybox init
  783 root       0:02 {multicast-rtp} /usr/bin/python3 /etc/init.extra/multicas
  789 root       0:00 rpcbind
  809 root       0:00 [lockd]
  811 root       0:00 [nfsd]
  812 root       0:00 [nfsd]
  813 root       0:00 [nfsd]
  814 root       0:00 [nfsd]
  815 root       0:00 [nfsd]
  816 root       0:00 [nfsd]
  817 root       0:00 [nfsd]
  818 root       0:00 [nfsd]
  979 root       0:00 /usr/sbin/ntpd -n -I eth0 -p 0.pool.ntp.org
  982 root       0:00 minisatip5 -f -g -X 0 -u 0:0-1210,1:1-1420,2:2-1680,3:3-2
  985 root       0:00 [flush-8:0]
  986 root       0:00 -sh
  987 root       0:00 ps

~ # logread
Jan  1 12:00:00 (none) syslog.info syslogd started: BusyBox v1.24.1
Jan  1 12:00:01 (none) local0.notice root: AXE drivers load start
Jan  1 12:00:02 (none) local0.notice root: AXE drivers load finish
Jan  1 12:00:03 (none) local0.notice root: Unpacking package /mnt/data/satip-axe/packages/Python-3.5.1-1.tar.gz
Jan  1 12:00:05 (none) local0.notice root: Mounting sda : /media/sda
Jan  1 12:00:05 (none) local0.notice root: Mounting sda1 : /media/USB
Jan  1 12:00:06 (none) local0.notice root: ... sda1 mounted using vfat filesystem (nfsd exported)
Jan  1 12:00:08 (none) local0.notice root: Unpacking package /mnt/data/satip-axe/packages/multicast-rtp-1.tar.gz
Jan  1 12:00:08 (none) daemon.info init: reloading /etc/inittab
Jan  1 12:00:08 (none) daemon.info init: starting pid 767, tty '': '/etc/init.d/network'
Jan  1 12:00:08 (none) daemon.info init: starting pid 768, tty '': '/etc/init.d/ntpd'
Jan  1 12:00:08 (none) daemon.info init: starting pid 769, tty '': '/etc/init.d/nfsd'
Jan  1 12:00:08 (none) daemon.info init: starting pid 770, tty '': '/etc/init.d/satip'
Jan  1 12:00:08 (none) daemon.info init: starting pid 771, tty '': '/etc/init.d/telnetd'
Jan  1 12:00:08 (none) daemon.info init: starting pid 772, tty '': '/etc/init.d/dropbear'
Jan  1 12:00:08 (none) daemon.info init: starting pid 773, tty '': '/etc/init.d/inetd'
Jan  1 12:00:08 (none) daemon.info init: starting pid 775, tty '': '/etc/init.d/crond'
Jan  1 12:00:08 (none) daemon.info init: starting pid 777, tty '': '/etc/init.d/oscamd'
Jan  1 12:00:08 (none) daemon.info init: starting pid 779, tty '': '/etc/init.d/customd'
Jan  1 12:00:08 (none) daemon.info udhcpc[767]: udhcpc (v1.24.1) started
Jan  1 12:00:08 (none) daemon.info init: starting pid 783, tty '': '/etc/init.extra/multicast-rtp'
Jan  1 12:00:08 (none) local0.notice root: DHCP deconfig
Jan  1 12:00:09 (none) cron.info crond[775]: crond (busybox 1.24.1) started, log level 8
Jan  1 12:00:09 (none) authpriv.warn dropbear[772]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jan  1 12:00:09 (none) authpriv.info dropbear[772]: Not backgrounding
Jan  1 12:00:09 (none) local0.notice root: Setting STV6210 gain to 8
Jan  1 12:00:09 (none) daemon.warn mountd[769]: Kernel does not have pseudo root support.
Jan  1 12:00:09 (none) daemon.warn mountd[769]: NFS v4 mounts will be disabled unless fsid=0
Jan  1 12:00:09 (none) daemon.warn mountd[769]: is specfied in /etc/exports file.
Jan  1 12:00:09 (none) daemon.notice mountd[769]: Version 1.3.3 starting
Jan  1 12:00:09 (none) daemon.info udhcpc[767]: Sending discover...
Jan  1 12:00:12 (none) daemon.info udhcpc[767]: Sending discover...
Jan  1 12:00:12 (none) daemon.info udhcpc[767]: Sending select for 192.168.1.30...
Jan  1 12:00:12 (none) daemon.info udhcpc[767]: Lease of 192.168.1.30 obtained, lease time 43200
Jan  1 12:00:12 (none) local0.notice root: DHCP bound ('192.168.1.30' 'broadcast 192.168.1.255' 'netmask 255.255.255.0' | '192.168.1.1' '192.168.1.1') replacing ''
Jan  1 12:00:12 (none) user.notice minisatip5: Setting unicable adapter 0 slot 0 freq 1210
Jan  1 12:00:12 (none) user.notice minisatip5: Setting unicable adapter 1 slot 1 freq 1420
Jan  1 12:00:12 (none) user.notice minisatip5: Setting unicable adapter 2 slot 2 freq 1680
Jan  1 12:00:12 (none) user.notice minisatip5: Setting unicable adapter 3 slot 3 freq 2040
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: minisatip version 0.5.50-axe102, compiled with s2api version: 0501 (AXE)
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built without dvbcsa
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built without CI
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built without dvbapi
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built with AES (OpenSSL)
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built without tables processing
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built with satip client
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built with linux dvb client
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built with backtrace
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Built without netceiver
Jan  1 12:00:12 (none) daemon.notice minisatip[982]: Initializing with 4 devices
Jan  1 12:00:13 (none) local7.info multicast-rtp: Version 0.1
Jun  6 18:32:04 (none) cron.err crond[775]: time disparity of 752071 minutes detected
Jun  6 18:33:06 (none) auth.info login[986]: root login on 'pts/0'

~ # netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:37              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:53703           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:7               0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:41160           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:554             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:13              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:54510           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:56089           0.0.0.0:*               LISTEN
tcp        0      0 192.168.1.30:554        192.168.1.187:17905     ESTABLISHED
tcp        0      0 192.168.1.30:8080       192.168.1.187:28612     TIME_WAIT
tcp        0      0 192.168.1.30:8080       192.168.1.8:58077       TIME_WAIT
tcp        0      0 192.168.1.30:8080       192.168.1.8:58078       TIME_WAIT
tcp        0      0 192.168.1.30:8080       192.168.1.8:58076       TIME_WAIT
tcp        0      0 :::59218                :::*                    LISTEN
tcp        0      0 :::22                   :::*                    LISTEN
tcp        0      0 :::23                   :::*                    LISTEN
tcp        0    235 ::ffff:192.168.1.30:23  ::ffff:192.168.1.20:59244 ESTABLISHED
udp        0      0 0.0.0.0:2049            0.0.0.0:*
udp        0      0 0.0.0.0:46081           0.0.0.0:*
udp        0      0 0.0.0.0:7               0.0.0.0:*
udp        0      0 0.0.0.0:13              0.0.0.0:*
udp        0      0 0.0.0.0:37              0.0.0.0:*
udp        0      0 0.0.0.0:46383           0.0.0.0:*
udp        0      0 0.0.0.0:34744           0.0.0.0:*
udp        0      0 0.0.0.0:952             0.0.0.0:*
udp        0      0 0.0.0.0:50240           0.0.0.0:*
udp        0      0 239.255.255.250:1900    0.0.0.0:*
udp        0      0 0.0.0.0:1900            0.0.0.0:*
udp        0      0 0.0.0.0:111             0.0.0.0:*
udp        0      0 192.168.1.30:5500       192.168.1.187:3456      ESTABLISHED
udp        0      0 192.168.1.30:5501       192.168.1.187:3457      ESTABLISHED
udp        0      0 :::59609                :::*
udp        0      0 :::123                  :::*
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING       2591 /var/run/rpcbind.sock
unix  9      [ ]         DGRAM                      1006 /dev/log
unix  3      [ ]         STREAM     CONNECTED       4227
unix  3      [ ]         STREAM     CONNECTED       4226
unix  2      [ ]         DGRAM                      4225
unix  2      [ ]         DGRAM                      4213
unix  2      [ ]         DGRAM                      2794
unix  2      [ ]         DGRAM                      2656
unix  2      [ ]         DGRAM                      2646
unix  2      [ ]         DGRAM                      2599
unix  2      [ ]         DGRAM                      2589
~ #
192.168.1.187 it"s Panasonic TV

**Comment by perexg** [comment]
If TVH with RTP/AVP/TCP enabled (embedded RTSP data mode) works, the problem is in the ethernet packet loss as I wrote before.

**Comment by 9000h** [comment]
but "autoneg off" you should take in account that you have to make sure you need to set the same parameters on the R1 and the switch

**Comment by paluseb** [comment]
How can I check if I turned off auto negotiation network connection?

**Comment by paluseb** [comment]
@perexg help me. What I can do? Why TVH don't shows minisatip5? minisatip workd fine.

**Comment by perexg** [comment]
Replace '-X 0' with '-U 0' for minisatip5. This parameters is different ('-X' option is for the XML file - which explains /0 in URL for minisatip5).
