### ISSUE TITLE
network connection

### ISSUE THREAD

**Issue by paluseb** [perexg/satip-axe#68]
You may try to force 100M connection using 'ethtool -s eth0 speed 100 autoneg off' in the satip-axe firmware.
I use this command bat now I want switch to 1000M. 
I try this command:
ethtool -s eth0 speed 1000 duplex full
but is don't work. How I can switch network conection to 1000M and autoneg on?

**Comment by perexg** [comment]
'ethtool -s eth0 autoneg on' or 'reboot'
