### ISSUE TITLE
Web UI not responding

### ISSUE THREAD

**Issue by gedl** [perexg/satip-axe#73]
Hi,

I tried this firmware today but am having trouble accessing the web ui on http://<ip>:8080

The request just hangs, I get no response whatsoever.

I am missing something ? Using satip-axe-201605311610-12 on a TS DIGIBIT R1

I am able to login via ssh without any problem.

**Comment by NemoN** [comment]
same here

**Comment by perexg** [comment]
The minisatip has no status page. The web server is serving only desc.xml (http://satip:8080/desc.xml) and jpeg images. If you like to see the status page, disable minisatip and enable minisatip5.
