### ISSUE TITLE
Help to compile

### ISSUE THREAD

**Issue by tnds82** [perexg/satip-axe#77]
Can you help me to compile in Ubuntu or other system please?

Regards

**Comment by CvH** [comment]
@tnds82 is https://github.com/perexg/satip-axe/blob/master/README.md not working ?

**Comment by tnds82** [comment]
Ok. Can you help me ? I need to update minisatip binary to make some test

**Comment by rucati** [comment]
Hi, in launchpad, frodo build minisatip for ubuntu, https://launchpad.net/~frodo-vdr/+archive/ubuntu/main

**Comment by tnds82** [comment]
I need build minisatip for satip-axe with ARCH SH4

**Comment by perexg** [comment]
@tnds82 : Follow requirements in https://github.com/perexg/satip-axe/blob/master/README.md . That's the build environment I'm using to build the whole firmware. You may expect little issues, but if you develop something in linux, it's easy to go through.
