### ISSUE TITLE
Setup with Tvheadend

### ISSUE THREAD

**Issue by MarhyCZ** [perexg/satip-axe#78]
Hi,
probably many people are using this great firmware as a SAT>IP client with Tvheadend. Would it be possible to maybe add to this wiki optimal settings of a tuner in Tvheadend? 
Like Full mux RX mode supported, PIDs in setup, Force pilot for DVB-S2, addpids/delpids supported, PIDs 21 in setup, Maximum PIDs, Send full PLAY cmd, etc..
It´s more of a suggestion than issue, but I think it would help beginners like me :)

**Comment by perexg** [comment]
Done.
