### ISSUE TITLE
LO1/LO2 frequency

### ISSUE THREAD

**Issue by arrobar** [perexg/satip-axe#82]
To see some channels in Spain I need to change the LO1 / LO2 frequency to 9750/9750 on my DIGIBIT r1.
Which modifier should I use?
I currently use MINISATIP5_OPTS = "-L 0: 1,0:2,0:3"  

Regards

**Comment by perexg** [comment]
Unfortunately, this is not supported with minisatip versions used in satip-axe. Pls, wait for minisatip 0.7.

**Comment by arrobar** [comment]
Thanks for your quick response. I'll wait for the new version.

**Comment by flotux2** [comment]
> Pls, wait for minisatip 0.7.
Does it mean we can expect further development of satip-axe in 2017? That would be really great!

**Comment by perexg** [comment]
Yes, in few days. Actually, I'm finishing my other delayed jobs from my backlog and I expect to look into satip-axe / latest minisatip in next days.

**Comment by perexg** [comment]
The build with minisatip7 (0.7.4) is available in https://github.com/perexg/satip-axe/issues/65 .
