### ISSUE TITLE
Feature request: Add rsyslog

### ISSUE THREAD

**Issue by jlazkano** [perexg/satip-axe#88]
Is it possible to add rsyslog to send all logs to a central server?

Regards.

**Comment by madmartin** [comment]
Hi @jlazkano,
I am just visiting this project (not using it yet) - so I give only an advice: rsyslog would probably far too big for an embedded device. 
But the feature you request is already implemented in busybox. Maybe the busybox compile configuration must be changed to produce binaries like "syslogd" and "logger".  The syslogd binary can then send logs to a remote computer. Read more on 
https://busybox.net/downloads/BusyBox.html
Bye
Martin

**Comment by jlazkano** [comment]
Thanks!

Is it possible to add it in the firmware compilation?

Kind regards.

**Comment by perexg** [comment]
There's already syslogd binary (and it's being used). The only missing part is to allow the remote logging throught the config files.

**Comment by jlazkano** [comment]
Thanks perexg,

Is it possible to add it?

Regards.

**Comment by perexg** [comment]
Fixed in new build 15.
