### ISSUE TITLE
4 unicable LNBs for Digibit R1?

### ISSUE THREAD

**Issue by tipexfm** [perexg/satip-axe#92]
Hello,

First of all I'd like to thank the developer of this firmware; it's because of it that I'm thinking of buying a Digibit R1.

I currently have 4 dishes, pointed to 4 different satellites positions.
I'd like to install a unicable LNB into each parabole. I've seen on the GitHub page (https://github.com/perexg/satip-axe/blob/master/dist/minisatip.md) that it supports unicable LNBs. My question is, if I install 4 unicable LNBs (one in each RF input), all tuners could tune to any LNB?

I want to avoid having to buy 4*Quad LNBs and 4* 4x1 switches (DiseqC) to be able to tune all satellites from any of the tuners...

Thank you! :)

**Comment by perexg** [comment]
> My question is, if I install 4 unicable LNBs (one in each RF input), all tuners could tune to any LNB?

Yes, https://github.com/perexg/satip-axe/blob/master/dist/minisatip.md 'Multiple unicable groups'
